#!/bin/sh
# $Id: esx-df,v 1.1 2012/03/07 02:25:46 friedman Exp $

mdf()
{
  local label
  for label in /vmfs/volumes/*; do
    test -L "$label" || continue
    local volume=`readlink "$label"`
    local sedstr="s=$volume=${label##*/}=;$sedstr"
  done

  local fmt="%-10s  %12s  %12s %12s %4s %s\n"
  df | sed "$sedstr" |
    while read fstype blocks used avail pct mounted; do
      printf "$fmt" "$fstype" "$blocks" "$used" "$avail" "$pct" "$mounted"
    done
}

mdf "$@"

# eof
